import type { Metadata } from "next";
import Header from "@/components/globals/Header";
import Footer from "@/components/globals/Footer";
import { UserStoreProvider } from "@/lib/store/user-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserStoreProvider>
          <Header />
          {children}
          <Footer />
        </UserStoreProvider>
      </body>
    </html>
  );
}
